export const SHARED_PASSWORD = 'haphuong';

export const LETTERS: string[] = [
  "💌 Ngày 1: Chúc em một ngày 20/10 thật vui vẻ và luôn hạnh phúc. Không chỉ ngày hôm nay mà là mãi về cả sau này nhé! Nếu em rảnh mỗi ngày có thể mở một bức thư phía dưới để đọc nha, em cũng có thể trả lời bằng cách nhấp nút phản hồi phía dưới.",
  "🌅 Ngày 2: Chúc em ngày mới vuiii! Mà em đọc hết sách anh gửi chưaaa, dạo này rảnh hơn rồi nên anh cũng muốn khôi phục lại thói quen đọc sách, nếu em rảnh có thể gởi ý cho anh một số quyển sách hay với nhá!!!!. ✨",
  "🌅 Ngày 3: Mấy quyển đó anh đọc hết lâu rồi á =)) Nói chưa đọc hết để sau có cớ nói chuyện với em thôi!!! Sách em cứ giữ đi, sau này có dịp nào anh về lại Đà Lạt thì tính tiếp. Anh đang muốn tìm thêm sách để đọc lúc rảnh á, em có đề xuất quyển nào hay không. ✨",
  "🌅 Ngày 4: Anh cũng có đọc sách của Bác NNA (Trại Hoa Vàng với Hạ Đỏ, Mắt Biếc) mà không có hợp gu cho lắm =)) Anh cũng có đọc sách của Murakami (Sau nửa đêm và 1Q84) sẽ đọc thử của Han Kang search thấy có vài quyển cũng hay hay, cảm ơn em nhìu nhìu. Anh có thấy em hay mất ngủ với đau dạ dày, hồi trước anh cũng vậy mà uống trà gừng vô thấy cũng cải thiện á, em có muốn uống thử trà không? Anh biết có một quán trà gừng siu ngon ",
  "🌅 Ngày 5: Troi vậy mà anh coi locket cảm giác em lúc nào cũng nhiềuu năng lượng aay, sao hay vậy !!! Đà Lạt giờ chắc đang chuyển đông rồi nhỉ, có lạnh không? Nhớ thời tiết Đà Lạt quá trời luôn. Em có kế hoạch gì cho mùa đông này chưa...",
  "🌅 Ngày 6: Ngày hôm nay của em thế nào, tuyệt vời khongg? H..Thì anh cũng có 1 món quà nhỏ tặng em nhưng mà chắc 26 hoặc 27 nó mới tới nơi cơ. Anh cũng có nhìu kế hoạch cho đông này và cũng sẽ tìm cách để nằm ở một trong nhiều kế hoạch của em =))))))))",
  "🌅 Ngày 7: Anh khong biết nữa có cái gì đó khiến anh làm vậy đấy =))))) Em nhận được quà chưa, con mèo ấy. Anh thấy em từ hôm tựu trường rồi cơ mà mãi giữa năm mới tìm được in4, xong gần cuối năm mới dám add =))))))))))))) có khi tới giờ em cũm chưa có biết anh đâu ấy chứ he =)))",
  "🌅 Ngày 8: Từ từ sau này biếc cũng chưa có muộn. Nay em đi Bảo Lộc ha, chúc cho em có chuyến đi vừa học cũng là trải nghiệm đáng nhớ nhen. Mới được 8 ngày mà sắp hết content mất tiêu rồi (T_T)",
  "🌅 Ngày 9: Em cứ học điii, nào rảnh đọc cũng được mà việc học ưu tiên hơn cả với anh cũng chuẩn bị thi giữa kì rùi nên cũng có ít thời gian. Cảm giác như thời xưa gửi thư chim bồ câu ấy =)))))) anh thấy đợi thư cũng vui vui. Em có mún gắn được ảnh lên luôn không cho nó y chang gửi thư như hồi xưa thiệt =)))))",
  "🌅 Ngày 10: Thỉnh thoảng anh vô check thui à chứ cũng không hẳn là đợi á. Emm cứ tập trung học thuiii khi nào rảnh đọc cũng được mà. Để vài ngày xong rùi tích mấy chuyện vui vui kể anhhh nghe chung với cũng hay ấy chứ",
  "🌅 Ngày 11:Cũng zuiii, nhma anh vẫn đang tập thích nghi với môi trường sống ở Miền Bắc. Ở trong Nam từ nhỏ mọi người thoải mái quen rùi mà về đây thì nhiều cái phải sửa lắm luôn ấy mà được cái là người ở đây siêu siêu nhiệt tình luôn á nên là cũng dễ hòa nhập hơn. Mà em đã có dự định học ở trường ĐH nào chưa zạ?",
  "🌅 Ngày 12: Cũng nên cân nhắc thử á, nếu nó phù hợp với ngành của em học để phát triển công việc về sau thì nên thử. Mất một thời gian đầu nhớ nhà thui rồi về sau sẽ đỡ á.",
  "🌅 Ngày 13: Hôm qua anh shock giải tích ngất lâm sàn nên quên viết T.T (nếu chưa đọc thì em vòng lại ngày 12 đọc nhá). Hà nội sang thu rồi đẹp lắm luôn mà máy ảnh hỏng với kẹt lịch thi dài dài, troi oi tiếc lắm luôn. Chắc em cũng gần hết chuyến ''du học'' xa nhà rùi heee, fighting!!! a a a cho anh lập chuỗi tiktok với em nhó >.<",
  "🌅 Ngày 14: Anh chắc mà =)))) Mà đi dài vậy á hả anh cứ tưởng đi có 2 tuần thôi chứ. Đi xa mà dài z thì giữ sức khỏe cẩn thận nhá, hôm nào mất ngủ thì kêu anh anh hát bài chúc bé ngủ ngon cho nghe chắc là sẽ vui hoặc tỉnh hẳn =)))))",
  "🌠 Ngày 15: Mấy hôm nayy em sao rùi có gì vui có thể chia sẻ với anhh không? Bên anh dạo này lạnh quá trời, sắp vào đông rồii",
  "🌠 Ngày 16: Uay nghe dự báo thì bên em có ảnh hưởng của bão nhỉ, ưu tiên bảo vệ sức khỏe và bản thân nhá. Anh không biết có thể làm được gì không nhma nếu cần giúp gì thì đừng ngại nói với anh nhé ",
  "🌠 Ngày 17: Anhhh lụy mùa đông năm 12 quá trời luôn ấy. Nguyên khu vực có mỗi anh đậu vào TL nên 2 năm đầu lạc lõng lắm có 4 5 đứa bạn à, mà lên năm 12 chơi được với nguyên lớp luôn nên lụy thời gian đó cực kì T.T. Và bây giờ lại tiếp tục một mình nữa troi oiiiii",
  "🌠 Ngày 18: Anh có đọc được ở đâu đó một câu là: Thế giới của người lớn lại là nơi mà ai cũng muốn bé lại. Ngẫm lại thấy đúng ghê á trời, cố gắng leennn còn có thể tận hưởng 2 năm học sinh với 4 năm sinh viên nữa cơ mà nàng owiiii",
  "🌠 Ngày 19: Anh thấy cuộc sống đại học thú zị lắm á chứ, được tập trung học cái mình thích với lại cũng tiếp cận được nhiều văn hóa của bạn bè khắp nơi ấyy. Mà em có dự định học đại học nào chưaaa á.",
  "🌠 Ngày 20: Khong sao khong sao khi nào em rảnh thì coi cũng được mà. HNoi dạo này lạnh ghê luôn, anh bị viêm mũi dị ứng khó chịu quá T.T. Mấy hôm cũng mưa nhiều nữa, cứ hôm nào rảnh anh tính đi chụp ảnh mùa thu là lại mưa",
  "🌠 Ngày 21: Ui anh cảm ơn nhá. Đà Lạt lạnh nhưng mà kiểu se se lạnh nên anh cũng thích lắm luôn ấy! Cũng chẳng biết còn cơ hội nào để về lại không nữa :((. Em cũng cố gắng giữ gìn sức khỏe, mặc ấm nhá vậy mới thêm được một dấu ấn cho bản thân trong kì thi sắp tới.",
  "🌠 Ngày 22: Chỗ anh cũng vậy nè, sáng nào cũng 4 5h giờ dậy để đi bus mà toàn lạnh cóng, muốn cúp luôn ấy. Nếu mà lịch thi ổn thì anh cũng muốn về tham gia chung tay đón tết của trường T.T À anh có tặng em vài quyền sách á, anh thấy cũng hay lắm luonnn. Em coi như một món quà cho giáng sinh này ha", 
  "🌠 Ngày 23: Anh cũng vô ý quên mất chuyện này luôn T.T. Không biết trong hộp quà vừa rồi em có thấy mấy tấm ảnh chụp Hà Nội không nhỉ? Anh chỉ sợ lúc đóng gói người ta làm rơi mất thôi. Thú thật là anh hơi kém khoản giao tiếp nên muốn trò chuyện với em nhiều hơn mà cứ loay hoay chẳng biết bắt đầu từ đâu. Đợt em thi vừa rồi anh cũng định chúc em, nhưng mà anh xui xui sao á tại chúc ai cũng... nên lại thôi. Dù sao thì em cũng đã vất vả và cố gắng nhiều rồi mà ở xa z mà anh vẫn thấy sự nỗ lực của em, vẫn còn một năm nữa để thử sức mà, cố lên nhé! Chuyện cũ mình bỏ qua ha, dạo này em đang đọc sách gì rồi? Chẳng hiểu sao dạo này anh cứ thấy mất dần niềm vui khi đọc sách ấy, rất mong nhận được lời khuyên từ em. Và nếu em không bận thì mình tiếp tục chơi cái này nha hehe."
];
