export const SHARED_PASSWORD = 'haphuong';

export const LETTERS: string[] = [
  "💌 Ngày 1: Chúc em một ngày 20/10 thật vui vẻ và luôn hạnh phúc. Không chỉ ngày hôm nay mà là mãi về cả sau này nhé! Nếu em rảnh mỗi ngày có thể mở một bức thư phía dưới để đọc nha, em cũng có thể trả lời bằng cách nhấp nút phản hồi phía dưới.",
  "🌅 Ngày 2: Chúc em ngày mới vuiii! Mà em đọc hết sách anh gửi chưaaa, dạo này rảnh hơn rồi nên anh cũng muốn khôi phục lại thói quen đọc sách, nếu em rảnh có thể gởi ý cho anh một số quyển sách hay với nhá!!!!. ✨",
  "🌅 Ngày 3: Mấy quyển đó anh đọc hết lâu rồi á =)) Nói chưa đọc hết để sau có cớ nói chuyện với em thôi!!! Sách em cứ giữ đi, sau này có dịp nào anh về lại Đà Lạt thì tính tiếp. Anh đang muốn tìm thêm sách để đọc lúc rảnh á, em có đề xuất quyển nào hay không. ✨",
  "🌅 Ngày 4: Anh cũng có đọc sách của Bác NNA (Trại Hoa Vàng với Hạ Đỏ, Mắt Biếc) mà không có hợp gu cho lắm =)) Anh cũng có đọc sách của Murakami (Sau nửa đêm và 1Q84) sẽ đọc thử của Han Kang search thấy có vài quyển cũng hay hay, cảm ơn em nhìu nhìu. Anh có thấy em hay mất ngủ với đau dạ dày, hồi trước anh cũng vậy mà uống trà gừng vô thấy cũng cải thiện á, em có muốn uống thử trà không? Anh biết có một quán trà gừng siu ngon ",
  "🌅 Ngày 5: Troi vậy mà anh coi locket cảm giác em lúc nào cũng nhiềuu năng lượng aay, sao hay vậy !!! Đà Lạt giờ chắc đang chuyển đông rồi nhỉ, có lạnh không? Nhớ thời tiết Đà Lạt quá trời luôn. Em có kế hoạch gì cho mùa đông này chưa...",
  "🌅 Ngày 6: Ngày hôm nay của em thế nào, tuyệt vời khongg? H..Thì anh cũng có 1 món quà nhỏ tặng em nhưng mà chắc 26 hoặc 27 nó mới tới nơi cơ. Anh cũng có nhìu kế hoạch cho đông này và cũng sẽ tìm cách để nằm ở một trong nhiều kế hoạch của em =))))))))",
  "🌅 Ngày 7: Anh khong biết nữa có cái gì đó khiến anh làm vậy đấy =))))) Em nhận được quà chưa, con mèo ấy. Anh thấy em từ hôm tựu trường rồi cơ mà mãi giữa năm mới tìm được in4, xong gần cuối năm mới dám add =))))))))))))) có khi tới giờ em cũm chưa có biết anh đâu ấy chứ he =)))",
  "🌅 Ngày 8: Từ từ sau này biếc cũng chưa có muộn. Nay em đi Bảo Lộc ha, chúc cho em có chuyến đi vừa học cũng là trải nghiệm đáng nhớ nhen. Mới được 8 ngày mà sắp hết content mất tiêu rồi (T_T)",
  "🌅 Ngày 9: Em cứ học điii, nào rảnh đọc cũng được mà việc học ưu tiên hơn cả với anh cũng chuẩn bị thi giữa kì rùi nên cũng có ít thời gian. Cảm giác như thời xưa gửi thư chim bồ câu ấy =)))))) anh thấy đợi thư cũng vui vui. Em có mún gắn được ảnh lên luôn không cho nó y chang gửi thư như hồi xưa thiệt =)))))",
  "🌅 Ngày 10: Thỉnh thoảng anh vô check thui à chứ cũng không hẳn là đợi á. Emm cứ tập trung học thuiii khi nào rảnh đọc cũng được mà. Để vài ngày xong rùi tích mấy chuyện vui vui kể anhhh nghe chung với cũng hay ấy chứ",
  "🌅 Ngày 11:Cũng zuiii, nhma anh vẫn đang tập thích nghi với môi trường sống ở Miền Bắc. Ở trong Nam từ nhỏ mọi người thoải mái quen rùi mà về đây thì nhiều cái phải sửa lắm luôn ấy mà được cái là người ở đây siêu siêu nhiệt tình luôn á nên là cũng dễ hòa nhập hơn. Mà em đã có dự định học ở trường ĐH nào chưa zạ?"
 ];
